# Generated by Django 2.2.4 on 2019-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_cash',
            field=models.FloatField(default=5000.0),
        ),
    ]
