# Generated by Django 2.2.4 on 2019-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_cash',
            field=models.IntegerField(default=5000),
        ),
    ]
